const themeColors = {
  light: {
    color: '#000',
    bg: '#fff',
    background: '#EFEFEF',
    borderColor: '#ccc',
    placeholderColor: '#000',
    buttonBackground: '#007bff',
    inputColor: '#efefef',
    warningColor: 'red',
    loaderBackground: '#ffffff90',
    loaderColor: 'rgba(0, 0, 0, 0.54)',
    errorColor: 'red',
    iconButtonBackground: 'transparent',
    highlightBackground: '#00000010',
    primaryColor: '#04ab97',
    secondaryColor: '#686868',
    IconColor: '#808080',
    buttonTitleColor: '#fff',
    resultColor: '#FF9A00',
    recoveredColor: '#8aca2b',
    confirmedColor: '#8c6e01',
    DeathColor: '#e53935',
  },
  dark: {
    color: '#fff',
    bg: '#000',
    borderColor: '#fafafa',
    background: '#000',
    inputColor: '#00000050',
    placeholderColor: '#fafafa',
    buttonBackground: '#fafafa50',
    warningColor: 'red',
    loaderBackground: '#00000090',
    loaderColor: '#fff',
    errorColor: 'red',
    primaryColor: '#04ab97',
    iconButtonBackground: 'transparent',
    highlightBackground: '#ffffff10',
    IconColor: '#808080',
    buttonTitleColor: '#fff',
    resultColor: '#FF9A00',
    recoveredColor: '#8aca2b',
    confirmedColor: '#8c6e01',
    DeathColor: '#e53935',
  },
};

export {themeColors};
